### ISSUE TITLE
Push "End" key can't enter system setup menu when cpu low mode with np2x64w.exe

### ISSUE THREAD

**Issue by leoxxx** [SimK98/np21w#1]
Other 3 exes are O.K. Only np2x64w.exe has this bug.
Neko Project 21/W ver0.86 rev91

**Comment by SimK98** [comment]
This issue will be resolved in ver.0.86 rev.92.

**Comment by leoxxx** [comment]
> This issue will be resolved in ver.0.86 rev.92.

I have tested rev92β1, still error.
BTW, how to custom map key? My keyboard no key between "/?" key and right "shift⇧" key. So no "ロ" key. I want to remap a key for it.
![2024-02-10_102012](https://github.com/SimK98/np21w/assets/5364709/a610dd32-a25c-4813-81ea-0249fb1d6381)

It's similar to this one.
![111](https://github.com/SimK98/np21w/assets/5364709/0da1f256-7404-47a7-971a-5572a0fd650a)

Another question, why I set hard disk boot first no effect? I found it will be default when restart.

**Comment by SimK98** [comment]
> I have tested rev92β1, still error.

I will look into this issue again.

> BTW, how to custom map key? My keyboard no key between "/?" key and right "shift⇧" key. So no "ロ" key. I want to remap a key for it.

Unfortunately, I have no plans to support key remapping at this time. If there are too many requests, I will consider it.

> Another question, why I set hard disk boot first no effect? I found it will be default when restart.

Hot-swapping of HDDs is not allowed on PC-98. Therefore, whenever you change the HDD image, you must restart the virtual machine.

**Comment by SimK98** [comment]
> I have tested rev92β1, still error.

This has been revised in ver.0.86 rev.92 beta 2.

**Comment by leoxxx** [comment]
> > I have tested rev92β1, still error.
> 
> This has been revised in ver.0.86 rev.92 beta 2.

It' O.K. THX.
Anex86 can boot HDD befroe FDD when they are inserted at same time, just check the box before "HDD -> FDD".
